language: minimal
os: linux
dist: bionic

install:
  - sudo apt update
  - sudo apt install apt-transport-https ca-certificates curl git software-properties-common

script:
  - ./install-root.sh

after_script:
  - echo "The resulting log:"
  - cat /tmp/boo.log
